config/routes.rb
Rails.application.routes.draw do
  devise_for :users
#  Prefix        Verb   URI Pattern                         Controller#Action
#  tweets             GET    /tweets(.:format)                    tweets#index
#                     POST   /tweets(.:format)                    tweets#create
#new_tweet            GET    /tweets/new(.:format)                tweets#new
#edit_tweet           GET    /tweets/:id/edit(.:format)           tweets#edit
#   tweet             GET    /tweets/:id(.:format)                tweets#show
#                     PATCH  /tweets/:id(.:format)                tweets#update
#                     PUT    /tweets/:id(.:format)                tweets#update
#                     DELETE /tweets/:id(.:format)                tweets#destroy

# tweet_comments      POST   /tweets/:tweet_id/comments(.:format) comments#create
# comments            POST   /comments(.:format)                  comments#create

# 検索機能のルーティング
# search_tweets_path	GET	   /tweets/search(.:format)	tweets#search


  # commentをどのtweetのものかを紐づけるため、親子関係のresourcesとする
  # これにより、commentに紐づいているtweetのidもコントローラーに引き継ぐことができる
  resources :tweets do
    resources :comments, only: :create

    # ７つのアクションとは別のアクションを設定(urlを任意に設定→「url名_tweets_path」をビューに設定)
    # collectionはidなし、memberはidあり
    collection do
      get 'search'
    end
    
  end
  resources :users, only: :show
  
    #以下は同じ意味
  # resources :tweets, only: :index
  # get 'tweets', to: 'tweets#index'

  # ---------------------------------

  # /(localhost3000のルート)をindexに変更する
  # 基礎では、localhost3000/tweetで繋いでいたが、今回はlocalhost3000で繋ぐ
  root to: 'tweets#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  # commentに対するuserは、1対1で紐付け
  belongs_to :user

  # commentに対するtweetは、1対1で紐付け
  belongs_to :tweet

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # 空のtextを登録できなくする validates(検証)
  # 投稿完了ページに飛ぶが、実際は登録されない
  validates :text, presence: true

  # tweetに対するuserは、1対1で紐付け
  belongs_to :user

  # tweetに対するcommentは、1対多で紐付け
  has_many :comments

  # indexの検索ワード→ルーティング(search)→コントローラーのsearchアクション
  # 以下のインスタンスメソッドは、コントローラーのsearchアクションから呼び出す
  # テーブルとのやりとりは、モデル内のメソッドを通じて行う
  # 検索ワードをパラメータとして引き継いできたsearchに何か入っていれば、
  # searchの値を含んだtweetテーブルのデータを取得
  # searchに何も入っていなければ、全てのtweetテーブルのデータを取得
  def self.search(search)
    if search
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # userに対するtweetは、1対多で紐付け
  has_many :tweets

  # userに対するcommentは、1対多で紐付け
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # deviseコントローラーに関連する処理の場合に行う(サインイン等)
  # ※ deviseコントローラーは編集不要のため、コマンドでファイルをコピーしていない
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

    # deviseのストロングパラメータは編集不可、共通コントローラーで定義
    # よって、devise_parameter_sanitizerメソッドを使用
    # 新たに定義するプライベートメソッドの中で使用
    # deviseのUserモデルを利用したパラメーターを取得
    
    # 以下、deviseの処理名≒アクション名
    # :sign_in	サインイン（ログイン）    の処理を行うときのuserモデルの要求
    # :sign_up	サインアップ（新規登録）  の処理を行うときのuserモデルの要求
    # :account_update	アカウント情報更新 の処理を行うときのuserモデルの要求

  def configure_permitted_parameters  
    #サインアップの時、コマンドで追加した「nickname」カラムの要求許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # tweets/showからルーティングへ引き継いだデータを登録
  # 登録データを変数に代入し、リダイレクトで変数のid(コメントしたtweet)に対するtweetモデルのshowアクションを行う
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private

  # commentテーブルは、text、user_id、tweet_idのみ許可
  # user_idは、ログインユーザーのid tweet_idは、選択中のtweetのidをここでセットするため、mergeを使用している
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

#test

  # 該当アクションの時は、対象id投稿データを@tweetに入れる処理が同じため、まとめる
  # editとshowの、対象id投稿データを@tweetに入れる処理が同じため、まとめる

  before_action :set_tweet, only: [:edit, :show]
  # 該当アクションの時は、未ログイン時にindexへリダイレクトするのを除外
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    # Tweetテーブル全データ取得→紐づいたUserテーブルも全て取得
    # includeにより、Tweetテーブル全てと、紐づいたテーブル全てを取得できる
    # レコード作成日を指定し、降順で並び替え
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    # 投稿ページから新しくデータベースに登録する空のレコードを生成
    # form_withのmodelでレコードが空か判断するために定義
    # new.htmlに引き渡すため、@をつける
    @tweet = Tweet.new
  end

  def create
    # new.html→ルーティングより受け渡されたパラメータをテーブルに保存
    Tweet.create(tweet_params)
  end

  def destroy
    # index.html→ルーティングのdeleteメソッドにidを渡して、そのidを指定して削除
    # テーブル削除時の投稿データは、このメソッドでしか使用しないため、@をつけない
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    # index.html→ルーティングで受け取ったidの投稿をeditビューのフォームで編集できるようにする
    # before_actionで、下記をアクション処理前に行うように定義
    # @tweet = Tweet.find(params[:id])
  end

  def update
    # edit.htmlにより、変更した対象のid投稿データを更新させる
    # 新規投稿と更新許可するカラムは同じ
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    # index.html→ルーティングで受け取ったidの投稿のみを表示
    # before_actionで、下記をアクション処理前に行うように定義
    # @tweet = Tweet.find(params[:id])

    # -----------------------------

    # 新しくコメントを投稿するレコード作成
    # 選択したtweetに対する全てのcommentを取得し(モデル親子関係)、tweet_idに紐づいたuser_idのuser情報も取得する
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  # indexの検索ワードをルーティングを通して引継ぎ、tweetモデルのインスタンスメソッドより、取得データ絞り込み
  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private
  def tweet_params
    # 受け取ったパラメータで、tweetテーブルのname,image,textのカラムデータしか受け取らなくする
    # require(要求) permit(許可)
    # 指定カラムの許可を行う時、どのテーブルの要求かを指定しないとエラーとなる
    # 後からコマンドで追加した、tweetテーブルのuser_idカラムの要求許可する(ハッシュをmergeで繋げる)
    # current_userにより、ログインユーザーの情報を取得する
    # 投稿者をuserテーブルのnicknameで管理するようになったため、tweetのnameが不要となる
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end


  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # /users/(user.id)
    # ログイン中のuser.nicknameと、紐づいているtweetテーブルの全データ取得しビューに受渡し
    # @nickname = current_user.nickname
    # @tweets = current_user.tweets

    # クリックされたユーザーのidデータを取得し、ニックネームとtweetテーブルをビューに受渡し
    # tweet.index→/users/(tweet.user.id)→ルーティングでid引継ぎ→user.controllerのshowアクション
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%# 全てのページのヘッダー部分のビュー(共通する箇所) %>
  <body>
    <header class="header">
      <div class="header__bar row">
        <%# pictweetをクリックしたら、index(ルート)に戻るように設定 %>
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>

        <%# 投稿するボタンがあった箇所に、ログインしている時、していない時で表示ボタンを分ける %>
        <%# user_signed_in?メソッドは、ユーザーがログインしていればtrueを、ログアウト状態であればfalseを返す %>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">

          <%# ヘッダーにニックネームを表示し、カーソルを合わせるとリスト表示 %>
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to "投稿する", new_tweet_path, class: "post" %>
          
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>

        <%# 投稿するをクリックしたら、投稿フォームのページに移動 %>
        <%# <a class="post" href="/tweets/new">投稿する</a> %>
        
      </div>
    </header>
    <%# ここでそれぞれのページのビューを表示 %>
      <%= yield %>
    <footer>
      <p>Copyright PicTweet 2019.</p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
      <%# 投稿者をuserテーブルのnicknameで管理するようになったため、tweetのnameが不要となる %>
      <%= form.text_field :image, placeholder: "Image Url" %>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>

      <%# 以下のものみたいに、tweetテーブルに指定したもの以外が送れてしまう為、ストロングパラメータで受け取るものを設定 %>
      <%# form.text_field :pass, placeholder: "password" %>
      <%= form.submit "SEND" %>

app/views/tweets/_tweet.html.erb
    <%# divのブロックレベル要素に背景の設定をし、テーブルの写真を表示 %>
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
      
      <%# 編集・削除など、投稿記事にリストボタン表示 %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%# /tweets/(tweet.id) %>
            <%= link_to '詳細', tweet_path(tweet.id), method: :get %>
          </li>
          <%# 「ユーザーがログインしている」かつ「投稿したユーザーである投稿だけに許可」の時のみ表示 %>
          <% if user_signed_in? && current_user.id == tweet.user_id %>
            <li>
              <%# 取得したidの投稿を表示させる %>
              <%# editコントローラーに対象id投稿データを送り、フォームで表示させて編集できるようにする %>
              <%# /tweets/(tweet.id)/edit %>
              <%= link_to '編集', edit_tweet_path(tweet.id), method: :get %>
            </li>
            <li>
              <%# eachメソッドにより、順番に投稿された記事の選択した番目idを取得して、リンク先の投稿を削除対象にする %>
              <%# <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %> 

              <%# tweet  DELETE /tweets/:id(.:format)    tweets#destroy %>
              <%# Prefixで表現する  prefix_path 式展開の{}が()になるので注意 %>
          
              <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
            </li>
          <% end %>
        </ul>
      </div>

      <%# 写真の中に題名をいれる %>
      <p><%= tweet.text %></p>

      <%# 写真の中に名前をいれる→写真の中に入れていた名前を、ニックネームに変更 %>
      <%# アソシエーションのテーブル紐付けにより、tweetのレコードをuserのレコードと紐付けできる %>
      <%# 「User.find(tweet.user_id)」を「tweet.user」と表現できる %>
      <%# tweet.nameを使用しなくなったため、user.nicknameに変更し、マイページに遷移 %>
      <%# a hrefにしている理由は、投稿者の後にnicknameをつけるのが困難なため %>
      <%# /users/(選択tweetを投稿したuserid)のurl→ルーティング→usersのshowアクション %>
      <span class="name">

        <%# 下記のパス指定でも可能 %>
        <%# <a href="<= user_path(@tweet.user.id) %>
        <a href="/users/<%= tweet.user.id %>">
          <span>投稿者</span><%= tweet.user.nickname %>
        </a>
      </span>
    </div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました</h3>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<%# 投稿編集画面 %>
<%# フォームはnew.htmlと同じ %>

<%# new.htmlとの違いは、コントローラーの@tweetにデータが入っているため、modelの取得HTTPメソッドが変わる %>
<%# @tweetには選択した投稿データが入っているため、nameやtextに表示される %>

<%# @tweetにデータが入っているため、modelにより、HTTPメソッドはupdateが自動的に選ばれる %>
<%# #    PATCH  /tweets/:id(.:format)      tweets#update  サーバのデータをブラウザから送られたデータに置き換え %>
<%# #    PUT    /tweets/:id(.:format)      tweets#update  更新・作成 %>

<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>編集する</h3>

      <%# 「_form.html.erb」の呼び出し、呼び出し先のformに、form_withメソッドのformを代入 %>
      <%= render partial: "form", locals: { form: form } %>
      
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="contents row">

<%# 検索用欄と検索ボタン追加 %>
<%# ルーティングでsearchアクションを設定することで、「url: search_tweets_path」を有効にする %>
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

 <%# eachメソッドにより、tweetテーブルをレコード単位で表示 %>
 <%# 各表示場所は、別途カリキュラムより保存したcssにより設定 %>
  <% @tweets.each do |tweet| %>

    <%# 「_tweet.html.erb」の呼び出し、呼び出し先のtweetに、eachメソッドのtweetを代入 %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>

  <% end %>
</div>

app/views/tweets/new.html.erb
<%# 新規投稿フォーム画面 %>

<div class="contents row">
  <div class="container">
    <%# 対応するnewコントローラーで、@tweet = Tweet.new(レコード生成する処理)を加える事で、 %>
    <%# form_withのmodelから自動で送信先のurlを指定する %>
    <%# コントローラーで@tweetを空にしているのは、modelで@tweetが空かどうか判断している為 %>
    <%# 基礎と同様に、フォームで入力したデータをパラメータとしてルーティングに送信 %>
    <%# ルーティングのresourcesメソッドのcreateからコントローラーのcreateアクションが動く %>

    <%# resources設定のPOSTを自動取得   POST  /tweets(.:format)  tweets#create %>


    <%= form_with(model: @tweet, local: true) do |form| %>
      <h3>投稿する</h3>

      <%# 「_form.html.erb」の呼び出し、呼び出し先のformに、form_withメソッドのformを代入 %>
      <%= render partial: "form", locals: { form: form } %>

    <% end %>

    <%# 基礎では、newアクションでは何もせず、新規投稿の送信されたデータをルーティングで受け取り、 %>
    <%# ルーティングよりコントローラーに送られたパラメータをcreateアクションのTweet.createで保存 %>

    <%# form_with url: "/tweets", method: :post, local: true do |form| %>
      <%# form.text_field :name %>
      <%# form.submit '投稿する' %>
    <%# end %>

app/views/tweets/search.html.erb
<%# 検索結果ビューとして表示 %>

<%# index画面と同じように、検索欄と検索ボタンを設置 %>
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<%# searchコントローラー、モデルのインスタンスメソッドで絞り込んだデータを表示 %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<%# index.htmlとほとんど同じ(1idの投稿になり、詳細ボタンが消えた) %>
<%# index.htmlと違ってeachメソッドを使用していないため、@必要 %>
<%# コメント欄追加 %>

<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <%# 「ユーザーがログインしている」かつ「投稿したユーザーである投稿だけに許可」の時のみ表示 %>
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_tweet_path(@tweet.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tweet_path(@tweet.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    
    <p><%= @tweet.text %></p>

    <span class="name">
      <%# tweet.nameを使用しなくなったため、user.nicknameに変更し、マイページに遷移 %>
      <%# a hrefにしている理由は、投稿者の後にnicknameをつけるのが困難なため %>
      
      <a href="/users/<%= @tweet.user.id %>">

        <%# 下記のパス指定でも可能 %>
        <%# <a href="<= user_path(@tweet.user.id) %>
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>

    </span>
  </div>

  <div class="container">

    <%# ユーザーがログインしていればコメントフォーム表示、していなければログイン喚起 %>
    <%# 条件は、if user_signed_in?でも代用可能 %>
    <% if current_user %>
      <%# @commentのフォームでは、親となる@tweetも記述しないと、pathが見つからないエラーが発生する %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>

    <div class="comments">
      <h4>＜コメント一覧＞</h4>
       <%# コメントの投稿者とコメントを表示 %>
       <%# コメントが空でもエラーが起きないようにする %>
       <%# 投稿者の名前をクリックすると、その投稿者のページに遷移 %>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>

  </div>

</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<%# マイページ→ログイン中のユーザーのツイート一覧表示 %>

<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>

  <% @tweets.each do |tweet| %>

  <%# 「_tweet.html.erb」の呼び出し、呼び出し先のtweetに、eachメソッドのtweetを代入 %>
  <%# usersフォルダ内にtweetsフォルダのerbを呼び出ししているため、「tweets/」を加える %>
  <%# 元々のコードになかった、詳細〜削除リストなども反映 %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>

    <%# 以下、元々のコード %>
    <%#div class="content_post" style="background-image: url(<%= tweet.image >);"> %>
      <%# <p><%= tweet.text ></p> %>
      <%# 投稿者をuserテーブルのnicknameで管理するようになったため、tweetのnameが不要となる %>
    <%# <div> %>

  <% end %>
</div>